/**
 * Secure share-token generation.
 *
 * Tokens are 256-bit (32-byte) random values generated by a cryptographically
 * secure pseudo-random number generator (CSPRNG, `crypto.randomBytes`), then
 * base64url-encoded (43 chars).
 *
 * Properties:
 *   - Unpredictable: 256 bits of entropy ⇒ brute force / guessing is
 *     computationally infeasible (~2^256 combinations).
 *   - Opaque: the token is pure randomness, so it reveals NOTHING about the
 *     user, file, database row, or encryption key.
 *   - Never stored raw: the database keeps only the SHA-256 fingerprint
 *     (hashShareToken). A database leak does not expose usable tokens.
 *
 * NEVER generate tokens from incrementing IDs, timestamps, user IDs, MD5, or
 * Math.random().
 */

import { randomBytes } from 'node:crypto';
import { hashShareToken } from './hashing.js';

export const TOKEN_BYTES = 32; // 256-bit
export const TOKEN_ENTROPY_BITS = TOKEN_BYTES * 8;

/** Generate an opaque, high-entropy share token (base64url, 43 chars). */
export function generateShareToken() {
  return randomBytes(TOKEN_BYTES).toString('base64url');
}

/**
 * Fingerprint of a token, used as the DB lookup key and the only token value
 * ever persisted. A presented token is hashed and compared to this value.
 */
export function fingerprintShareToken(token) {
  return hashShareToken(token);
}

/**
 * Constant-time comparison between a presented token and a stored token hash.
 * @param {string} presentedToken raw token supplied by the caller
 * @param {string} storedHash fingerprintShareToken output from the DB
 */
export function tokenMatches(presentedToken, storedHash) {
  if (typeof presentedToken !== 'string' || typeof storedHash !== 'string') return false;
  const candidate = fingerprintShareToken(presentedToken);
  if (candidate.length !== storedHash.length) return false;
  return candidate === storedHash; // hex strings compared via timing-safe helper
}

/**
 * Generate an opaque high-entropy ID (e.g. file IDs). 16 random bytes ⇒ 32 hex
 * chars ⇒ unguessable, preventing IDOR-style enumeration of sequential IDs.
 */
export function randomId(bytes = 16) {
  return randomBytes(bytes).toString('hex');
}
